require 'rubygems'
require 'bundler/setup'

require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet/version'
require 'puppet/vendor/semantic/lib/semantic' unless Puppet.version.to_f < 3.6
require 'puppet-lint/tasks/puppet-lint'
require 'puppet-syntax/tasks/puppet-syntax'
require 'metadata-json-lint/rake_task'
require 'rubocop/rake_task'

# These gems aren't always present, for instance
# on Travis with --without development
begin
  require 'puppet_blacksmith/rake_tasks'
rescue LoadError # rubocop:disable Lint/HandleExceptions
end

RuboCop::RakeTask.new

exclude_paths = [
  'bundle/**/*',
  'pkg/**/*',
  'vendor/**/*',
  'spec/**/*'
]

# Coverage from puppetlabs-spec-helper requires rcov which
# doesn't work in anything since 1.8.7
Rake::Task[:coverage].clear

Rake::Task[:lint].clear

PuppetLint.configuration.relative = true
PuppetLint.configuration.disable_80chars
PuppetLint.configuration.disable_class_inherits_from_params_class
PuppetLint.configuration.disable_class_parameter_defaults
PuppetLint.configuration.fail_on_warnings = true

PuppetLint::RakeTask.new :lint do |config|
  config.ignore_paths = exclude_paths
end

PuppetSyntax.exclude_paths = exclude_paths

desc 'Run acceptance tests'
RSpec::Core::RakeTask.new(:acceptance, :os) do |t, task_args|
  os = task_args[:os]

  case os
  when 'centos6'
    ENV['BEAKER_set']='centos-66-x64'
  when 'centos7'
    ENV['BEAKER_set']='centos-7-x64'
  when "debian"
    ENV['BEAKER_set']='debian-78-x64'
  when "ubuntu12"
    ENV['BEAKER_set']='ubuntu-1204-x64'
  when "ubuntu14"
    ENV['BEAKER_set']='ubuntu-1404-x64'
  else
    puts "Using the default nodeset"
  end
  ENV['BEAKER_destroy']='onpass'
  t.pattern = 'spec/acceptance'
end

desc 'Populate CONTRIBUTORS file'
task :contributors do
  system("git log --format='%aN' | sort -u > CONTRIBUTORS")
end

desc 'Run syntax, lint, and spec tests.'
task :test => [
  :metadata_lint,
  :syntax,
  :lint,
  :rubocop,
  :spec
]

RuboCop::RakeTask.new(:rubocop_debug) do |t|
  t.options = %w(-d)
end
